version: '3.8'
services:
  db:
    image: postgres:15
    container_name: tooshouse-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ToosHouseDeployment2026
      POSTGRES_DB: medusa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: tooshouse-redis
    restart: always

  backend:
    build: ./my-medusa-backend
    container_name: tooshouse-backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:ToosHouseDeployment2026@tooshouse-db:5432/medusa_db
      - REDIS_URL=redis://tooshouse-redis:6379
    ports:
      - "9000:9000"

  storefront:
    build:
      context: ./my-medusa-storefront
      args:
        - NEXT_PUBLIC_MEDUSA_BACKEND_URL=https://api.toolshouse.ir
    container_name: tooshouse-storefront
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
