// src/lib/categories.ts

export type Category = {
  name: string;
  handle: string;
  children?: Category[];
};

export const CATEGORIES: Category[] = [
  {
    name: "ابزارآلات دستی",
    handle: "abzaraalat-dsty-73",
    children: [
      { name: "جعبه ابزار", handle: "jabh-abzar-86" },
      { name: "آچار ها", handle: "aachar-ha-80" },
      { name: "عمومی", handle: "amwmy-1843" },
      { name: "انبر ها", handle: "anbr-ha-81" },
      { name: "چراغ قوه", handle: "chragh-qwh-2610" },
      { name: "مته دریل", handle: "mth-dryl-88" },
      { name: "نردبان", handle: "nrdban-2276" },
      { name: "کیف ابزار", handle: "kyf-abzar-85" },
      { name: "سیم چین", handle: "sym-chyn-2428" },
      { name: "انبردست", handle: "anbrdst-2429" },
      { name: "پیچ گوشتی دوسو", handle: "pych-gwshty-dwsw-2431" },
      { name: "قیچی لوله بر", handle: "qychy-lwlh-br-92" },
      { name: "پیچ گوشتی چهارسو", handle: "pych-gwshty-chharsw-2432" },
      { name: "سری پیچ گوشتی دریل", handle: "sry-pych-gwshty-dryl-87" },
      { name: "منگنه کوب", handle: "mngnh-kwb-94" },
      { name: "میخ اسکا و تیو", handle: "mykh-aska-w-tyw-2653" },
      { name: "قیچی مفتول بر", handle: "qychy-mftwl-br-2246" },
      { name: "دم باریک", handle: "dm-baryk-2430" },
      { name: "قاپک شیشه و سنگ", handle: "qapk-shyshh-w-sng-2401" },
      { name: "دستکش", handle: "dstksh-91" },
      { name: "کلا‌ه ایمنی", handle: "kla‌h-aymny-90" },
      { name: "قیچی ورق بر", handle: "qychy-wrq-br-2245" },
    ],
  },
  {
    name: "برند ها",
    handle: "brnd-ha-2329",
    children: [
      { name: "کنزاکس", handle: "knzaks-2335" },
      { name: "پی ای پی", handle: "py-ay-py-2333" },
      { name: "ان ای سی", handle: "an-ay-sy-2660" },
      { name: "تیوان", handle: "tywan-2334" },
      { name: "رونیکس", handle: "rwnyks-2331" },
      { name: "توسن", handle: "twsn-2330" },
      { name: "آروا", handle: "aarwa-2332" },
      { name: "ای پی ان", handle: "ay-py-an-2410" },
      { name: "دیوالت", handle: "dywalt-2361" },
      { name: "ماکیتا", handle: "makyta-2362" },
      { name: "میلواکی", handle: "mylwaky-2363" },
      { name: "ماکوته", handle: "makwth-2336" },
    ],
  },
  {
    name: "ابزار آلات بادی",
    handle: "abzar-aalat-bady-2387",
    children: [
      { name: "درجه باد", handle: "drjh-bad-2404" },
      { name: "جک سوسماری", handle: "jk-swsmary-2705" },
      { name: "بادپاش", handle: "badpash-2402" },
      { name: "میخ کوب بادی", handle: "mykh-kwb-bady-2386" },
      { name: "شیلنگ باد", handle: "shylng-bad-2455" },
      { name: "تلمبه باد", handle: "tlmbh-bad-2403" },
      { name: "بکس بادی", handle: "bks-bady-2305" },
      { name: "کوبلینگ باد", handle: "kwblyng-bad-2405" },
      { name: "پیسوله بادی", handle: "pyswlh-bady-2180" },
      { name: "منگنه کوب بادی", handle: "mngnh-kwb-bady-2385" },
    ],
  },
  {
    name: "ابزارآلات جوش وبرش",
    handle: "abzaraalat-jwsh-wbrsh-75",
    children: [
      { name: "تورچ فندکی", handle: "twrch-fndky-121" },
      { name: "ماسک و عینک جوشکاری", handle: "mask-w-aynk-jwshkary-2275" },
      { name: "سیم جوش و الکترود", handle: "sym-jwsh-w-alktrwd-2790" },
      { name: "دستگاه جوش", handle: "dstgah-jwsh-122" },
      { name: "انبرجوشکاری", handle: "anbrjwshkary-2299" },
      { name: "گونیا مغناطیسی", handle: "gwnya-mghnatysy-jwshkary-2306" },
      { name: "انبر اتصال جوشکاری", handle: "anbr-atsal-jwshkary-2300" },
      { name: "مانومتر", handle: "manwmtr-1759" },
      { name: "سر پیک برش", handle: "sr-pyk-brsh-124" },
      { name: "سر پیک جوش", handle: "sr-pyk-jwsh-123" },
    ],
  },
  {
    name: "ابزارآلات برقی",
    handle: "abzaraalat-brqy-74",
    children: [
      { name: "کمپرسور باد", handle: "kmprswr-bad-102" },
      { name: "کارواش", handle: "karwash-98" },
      { name: "فرز برقی", handle: "frz-brqy-95" },
      { name: "مینی فرز", handle: "myny-frz-2469" },
      { name: "فرز مینیاتوری", handle: "frz-mynyatwry-2443" },
      { name: "وینچ بالابر برقی", handle: "wynch-balabr-brqy-1951" },
      { name: "پیسوله برقی", handle: "pyswlh-brqy-101" },
      { name: "چکش تخریب", handle: "chksh-tkhryb-97" },
      { name: "دریل برقی", handle: "dryl-brqy-96" },
      { name: "مکنده و دمنده", handle: "mkndh-w-dmndh-103" },
      { name: "اتو لوله کشی", handle: "atw-lwlh-kshy-100" },
      { name: "پمپ و کف کش", handle: "pmp-w-kf-ksh-2238" },
      { name: "سشوار صنعتی", handle: "sshwar-snaty-99" },
      { name: "اره عمودبر", handle: "arh-amwdbr-137" },
      { name: "پروفیل بر و شیارزن", handle: "prwfyl-br-w-shyarzn-104" },
    ],
  },
  {
    name: "ابزار آلات شارژی",
    handle: "abzar-aalat-sharzhy-72",
    children: [
      { name: "دریل شارژی", handle: "dryl-sharzhy-125" },
      { name: "ویبره شارژی کاشی", handle: "wybrh-sharzhy-kashy-2661" },
      { name: "اره شارژی", handle: "arh-sharzhy-1832" },
      { name: "قیچی باغبانی شارژی", handle: "qychy-baghbany-sharzhy-2031" },
      { name: "کمپرسور باد شارژی", handle: "kmprswr-bad-sharzhy-2001" },
      { name: "کارواش شارژی", handle: "karwash-sharzhy-127" },
      { name: "فرز شارژی", handle: "frz-sharzhy-126" },
    ],
  },
  {
    name: "قفل و یراق آلات",
    handle: "qfl-w-yraq-aalat-78",
    children: [
      { name: "قفل دوچرخه و موتور", handle: "qfl-dwchrkhh-w-mwtwr-syklt-119" },
      { name: "قفل کتابی", handle: "qfl-ktaby-114" },
      { name: "قفل آویز", handle: "qfl-aawyz-115" },
      { name: "جک آرام بند", handle: "jk-aaram-bnd-113" },
      { name: "قفل برقی", handle: "qfl-brqy-117" },
      { name: "سیلندر قفل", handle: "sylndr-qfl-118" },
    ],
  },
  {
    name: "چسب و اسپری",
    handle: "chsb-w-aspry-2127",
    children: [
      { name: "اسپری", handle: "aspry-2128" },
      { name: "رنگ و رزین", handle: "rng-w-rzyn-2546" },
      { name: "چسب", handle: "chsb-2129" },
    ],
  },
  {
    name: "ابزار آلات اندازه گیری",
    handle: "abzar-aalat-andazh-gyry-2377",
    children: [
      { name: "کولیس", handle: "kwlys-2378" },
      { name: "تراز دستی", handle: "traz-dsty-2776" },
      { name: "متر دستی", handle: "mtr-dsty-82" },
      { name: "تراز لیزری", handle: "traz-lyzry-84" },
      { name: "متر لیزری", handle: "mtr-lyzry-83" },
    ],
  },
  {
    name: "ابزارآلات باغبانی",
    handle: "abzaraalat-baghbany-wkshawrzy-71",
    children: [
      { name: "قیچی باغبانی", handle: "qychy-baghbany-128" },
      { name: "بیلچه باغبانی", handle: "bylchh-baghbany-135" },
      { name: "سمپاش دستی", handle: "smpash-dsty-131" },
      { name: "سری آبپاش", handle: "sry-aabpash-130" },
      { name: "شمشاد زن", handle: "shmshad-zn-132" },
      { name: "اره باغبانی", handle: "arh-baghbany-129" },
      { name: "اره زنجیری برقی", handle: "arh-znjyry-brqy-133" },
      { name: "تبر", handle: "tbr-134" },
    ],
  },
  {
    name: "برق و الکترونیک",
    handle: "brq-w-alktrwnyk-79",
    children: [
      { name: "سراهی صنعتی", handle: "srahy-snaty-105" },
      { name: "پریز صنعتی", handle: "pryz-snaty-107" },
      { name: "دو شاخه صنعتی", handle: "dw-shakhh-snaty-106" },
    ],
  },
  {
    name: "صفحه سنگ فرز و سمباده",
    handle: "sfhh-sng-frz-w-smbadh-76",
    children: [
      { name: "صفحه سنگ فرز", handle: "sfhh-sng-frz-109" },
      { name: "الکتروپلیت و وکیوم پلیت", handle: "sfhh-alktrwplyt-w-wkywm-plyt-2444" },
      { name: "پرسلان بر", handle: "prslan-br-2419" },
      { name: "سمباده فلاپی", handle: "smbadh-flapy-108" },
    ],
  },
  {
    name: "قطعات یدکی",
    handle: "qtaat-ydky-abzaraalat-77",
    children: [
      { name: "سه نظام دریل", handle: "sh-nzam-dryl-111" },
      { name: "تبدیل دریل به فرز", handle: "tbdyl-dryl-bh-frz-2274" },
      { name: "باطری ابزار شارژی", handle: "batry-abzar-sharzhy-110" },
      { name: "تبدیل مینی فرز به اره", handle: "tbdyl-myny-frz-bh-arh-znjyry-2032" },
    ],
  },
];